### ISSUE TITLE
Invalid SKU?

### ISSUE THREAD

**Issue by aagult** [hunterbdm/ADCStockMonitor#1]
I was trying to add BA8920 and says Invalid SKU.

**Comment by hunterbdm** [comment]
Can you send a screenshot?

**Comment by aagult** [comment]
@hunterbdm 
![image](https://cloud.githubusercontent.com/assets/20647076/23576475/53a2ef08-0074-11e7-83a0-13ae0f560529.png)

**Comment by hunterbdm** [comment]
You might not be running it in python 3, download the updated repo and it
should say if that is the issue.

**Comment by aagult** [comment]
I have both Python 2.7 and 3.6 installed. Not sure if I need to configure something to make 3.6 as a default.

**Comment by hunterbdm** [comment]
do "python3 run.py". This should work assuming you have python 3 in your
PATH.

**Comment by aagult** [comment]
![image](https://cloud.githubusercontent.com/assets/20647076/23576579/863cfb68-0077-11e7-9324-258d13c6803f.png)

**Comment by hunterbdm** [comment]
Update to the latest version.

**Comment by aagult** [comment]
"Could not start: Python 3.x is required." It seems my default is 2.7. Wait let me figure it out.

**Comment by aagult** [comment]
Now I have Python36 as a default and this:
![image](https://cloud.githubusercontent.com/assets/20647076/23576680/f905d2ee-0079-11e7-8a71-3b373504c3a4.png)

**Comment by hunterbdm** [comment]
follow the readme

**Comment by aagult** [comment]
Thank you!
