### ISSUE TITLE
Yes, unfortunately this is not working on mac os x

### ISSUE THREAD

**Issue by shYter777** [hunterbdm/ADCStockMonitor#3]
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/qx/sy4vfdpj1yl07bhywnc99cx80000gn/T/pip-build-kog_zw5g/pygame/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/qx/sy4vfdpj1yl07bhywnc99cx80000gn/T/pip-mqhe94os-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/qx/sy4vfdpj1yl07bhywnc99cx80000gn/T/pip-build-kog_zw5g/pygame/

I am getting this error after pip3 install -r requirements.txt

**Comment by hunterbdm** [comment]
this does not work anymore
